apiVersion: v1
kind: PersistentVolume
metadata:
  name: spire-agent-datadir
  namespace: spire
  labels:
    type: local
    app: spire-agent
spec:
  # storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: spire
  name: spire-agent-datadir
  labels:
    app: spire-agent
spec:
  # storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
