apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtor-kafka
  labels:
    app: produtor-kafka
spec:
  selector:
    matchLabels:
      app: produtor-kafka
  template:
    metadata:
      labels:
        app: produtor-kafka
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: produtor-kafka
          image: silvamatteus/produtor-kafka:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WORKLOAD_API_SOCK_PATH
              value: unix:///run/spire/sockets/agent.sock
            - name: SPIFFE_TRUST_DOMAIN
              value: lsd.ufcg.edu.br
            - name: KAFKA_ID
              value: kafka
            - name: BROKER_ADDR
              value: "kafka:9092"
            - name: TOPIC
              value: $USERNAME
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
          resources:
            requests:
              memory: "15M"
            limits:
              memory: "50M"
      hostAliases:
        - ip: "10.11.19.213"
          hostnames:
            - "kafka"
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
